### ISSUE TITLE
How to pass recover option when subscribe to a channel

### ISSUE THREAD

**Issue by lsc20051426** [centrifugal/centrifuge-js#115]
https://centrifugal.github.io/centrifugo/transports/recovery/
Is there a way to pass the recover from client(as mention in above link) to fetching some history messages?

When server receives subscribe command with boolean flag recover set to true and offset, epoch set to values last seen by a client (see SubscribeRequest type in protocol definitions) it can try to find all missed publications from history cache. Recovered publications will be passed to client in subscribe Reply in correct order, and your publication handler will be automatically called to process each missed message.
-------
in Centrifuge-JS:
```
options = {recover: true,  offset: 6}
centrifuge.subscribe("channel", options, callback);
```
probably? 
or is there are some other ways to do it?

**Comment by FZambia** [comment]
@lsc20051426 hi, description in docs is about internal protocol which is only used for automatic recovery in case of network disconnects at moment.

But I understand what you mean – actually for there is rather old open pull request #44 that allows to what you are describing. But that pr was made for version 1 of centrifuge-js, so not actual at moment.

I did not merge it because I have not found enough motivation and live use case to extend API. Could you describe how you are planning to use this? Are you planning to save offset in localStorage? Why do you want this instead of asking database about actual state?

**Comment by lsc20051426** [comment]
you are right. we save offset in localStorage. 
- Give the offset when subscribe.
- save offset for channel when receiving a new message in local.

Here are some hacks for js code(just example):
```
-    value: function subscribe(channel, events) {
+    value: function subscribe(channel, events, options) {
       var currentSub = this._getSub(channel);
       if (currentSub !== null) {
         currentSub._setEvents(events);
@@ -1995,6 +1995,9 @@ var Centrifuge = exports.Centrifuge = function (_EventEmitter) {
         return currentSub;
       }
       var sub = new _subscription2.default(this, channel, events);
+      sub._recover = options.recover;
+      sub._recoverable = options.recoverable;
+      this._lastOffset[channel] = options.offset;
       this._subs[channel] = sub;
       sub.subscribe();
       return sub;
```

**Comment by FZambia** [comment]
Can you give a bit more use case description? Why do you need this instead of asking initial state from main application database?

**Comment by FZambia** [comment]
I think it's now available with https://github.com/centrifugal/centrifuge-js#subscribe-since-known-position
