### ISSUE TITLE
pure typescript implementation does not subscribe to channel

### ISSUE THREAD

**Issue by zkbitcoin** [centrifugal/centrifuge-js#199]
hello , doing simple call to connect and then subscribe to a channel , only connect gets callback subscribe does not 

import {Centrifuge} from "centrifuge";

// Use WebSocket transport endpoint.
const centrifuge = new Centrifuge('ws://n.n.n.n:8000/connection/websocket');

// Allocate Subscription to a channel.
const sub = centrifuge.newSubscription('test');

centrifuge.on('connected', function () {
    console.log('Connected to Centrifugo');
});

centrifuge.on('disconnected', function () {
    console.log('Disconnected from Centrifugo');
});

centrifuge.on('subscribed', function () {
    console.log('subscribed to Centrifugo');
});

centrifuge.on('publication', function (ctx) {
    console.log('Publication, time = ' + ctx.data.time);
});

// Trigger subscribe process.
sub.subscribe();

// Trigger actual connection establishement.
centrifuge.connect();

--- server logs show (below) but callback to the client is not happening (centrifuge.on('subscribed', function ()...)

client authenticated
client subscribed to channel channel=test

**Comment by FZambia** [comment]
Hello, the reason is that you are using centrifuge.on(subscribed) instead of sub.on(subscribed). So you are using server-side subscription callbacks, instead of client-side subscription callback.

Just change code to use `sub.on('subscribed')` and `sub.on('publication')` - and all should work fine.

Also, I suggest listening to centrifuge.on('connecting') and sub.on('subscribing') events. See SDK spec mentioned in the top of README

**Comment by FZambia** [comment]
Closing, hope an issue solved
