### ISSUE TITLE
Token refresh does not work correctly

### ISSUE THREAD

**Issue by xoqs** [centrifugal/centrifuge-js#202]
Hi! 
After calling `getToken`, the `token` is not updated. Apparently this is because when disconnected due to (`connection expired` / `3005`) the `_refreshRequired` field is not updated. As a result, we will never update the token and each time we will use the one that was either specified in `config.token` or the one that was returned by `getToken` during the first call

**Comment by FZambia** [comment]
Hello,

`3005` is a non-terminal disconnect code, so SDK should reconnect to a server upon receiving it, upon reconnect SDK should get `token expired` error (code 109) and `_refreshRequired` flag should be set. After that, on next connect attempt, `getToken` should be called to load new token since `_refreshRequired` is set.

In my opinion SDK should survive this situation even with current code. So whether I am missing sth or you hit sth different.

**Comment by FZambia** [comment]
Closing, since no response from op and I did not understand the issue without steps to reproduce.
