### ISSUE TITLE
Question:about connect token and Subscribe token

### ISSUE THREAD

**Issue by lengjunbin-trec** [centrifugal/centrifuge-js#206]
I want to subscribe a private channel.I checked the doc need provide a JWT token.otherwise it will return `103: permission denied`.can I use connect token?I means connect and Subscribe share the same token.
centrifugo version is `4.0.1` certirfugo-js version is `3.0.1`

**Comment by FZambia** [comment]
Hello @lengjunbin-trec 

It's not possible to reuse the same token for connecting and for subscribing. This is intentional due to security reasons - connection JWT can't contain `channel` claim, subscription JWT must contain `channel` claim.

There is sth similar to what you are asking about in [Centrifugo PRO channel capabilities](https://centrifugal.dev/docs/pro/capabilities) feature. It's possible to give permissions to the client to subscribe to some channels. But for the OSS - you need to use separate token for a client-side subscription to the private channel.

**Comment by lengjunbin-trec** [comment]
> Hello @lengjunbin-trec
> 
> It's not possible to reuse the same token for connecting and for subscribing. This is intentional due to security reasons - connection JWT can't contain `channel` claim, subscription JWT must contain `channel` claim.
> 
> There is sth similar to what you are asking about in [Centrifugo PRO channel capabilities](https://centrifugal.dev/docs/pro/capabilities) feature. It's possible to give permissions to the client to subscribe to some channels. But for the OSS - you need to use separate token for a client-side subscription to the private channel.

Thank you for your answer
