### ISSUE TITLE
Cannot read property 'transportName' of undefined

### ISSUE THREAD

**Issue by JeanCarriere** [centrifugal/centrifuge-js#26]
It happen in production that I get some errors of this kind.
```
this._transport.onopen = function () {
        self._transportClosed = false;
        self._reconnecting = false;
        if (self._useSockJS) {
            self._transportName = self._transport._transport.transportName;
            self._transport.onheartbeat = function(){
                self._restartPing();
            };
        } else {
            self._transportName = "raw-websocket";
```

**Comment by FZambia** [comment]
@JeanCarriere hmm... strange, it happen not every time right? Do you use latest centrifuge-js and SockJS 1.1.2?

**Comment by JeanCarriere** [comment]
No not every time. 
I use centrifuge-js 1.4.1 and sockjs 1.1.2

**Comment by FZambia** [comment]
Here we use SockJS client private variable to get current transport name - which is not a good way as this is not a part of public API. Just looked at SockJS source code - there is a way to avoid this. Instead of:
```
if (self._useSockJS) {
            self._transportName = self._transport._transport.transportName;
```
We can just write:
```
if (self._useSockJS) {
            self._transportName = self._transport.transport;
```
I'll make release with this change later today, this can probably fix an error. If you have a possibility to try it - it can help to avoid useless release.

**Comment by FZambia** [comment]
@JeanCarriere made 1.4.3 release with this change, please check it out.

**Comment by JeanCarriere** [comment]
👍

**Comment by FZambia** [comment]
@JeanCarriere I suppose it works? Feel free to reopen if you will have any issues.
