### ISSUE TITLE
[Question] How client can send a custom headers to centrifugo ?

### ISSUE THREAD

**Issue by duy-nguyen-ts** [centrifugal/centrifuge-js#270]
Hi @FZambia , I am using this client SDK in react-js to connect to centrifugo. I want client add a custom header then Centrifuge can proxy headers to Backend which I define in this config `proxy_http_headers`. I knew that it can be sent when creating connection, but I don't have the option such as `headers` when using it:
```
const centrifuge = new Centrifuge('ws://centrifuge.example.com/connection/websocket', {
    token: '<CONNECTION_TOKEN>'
});
```

**Comment by FZambia** [comment]
Hello @duy-nguyen-ts ,

Browser APIs do not allow setting custom headers to WebSocket connections. That's why there is no such option in centrifuge-js. But browsers append Cookie automatically to WebSocket requests to the same domain - that's why there is still an option for Centrifugo to proxy Cookie to the backend.

There is also a `data` field if Centrifuge constructor options - https://github.com/centrifugal/centrifuge-js/blob/c825ddcc5056a8660c694f6f79fee7c73d2907a4/src/types.ts#L101 - you can use it to pass some arbitrary information to your backend when using connect proxy of Centrifugo:

```javascript
const centrifuge = new Centrifuge('ws://centrifuge.example.com/connection/websocket', {
    token: '<CONNECTION_TOKEN>',
    data: {"key": "value"}
});
```

And it will be available [inside connect request payload](https://centrifugal.dev/docs/server/proxy#connect-proxy:~:text=client%20on%20connect)-,data,-JSON)

**Comment by FZambia** [comment]
For those who come across this issue, for non-browser environment (i.e. development with React Native) it's possible to use custom WebSocket constructor to pass custom headers, it's [described in README](https://github.com/centrifugal/centrifuge-js?tab=readme-ov-file#custom-websocket-constructor)
