### ISSUE TITLE
require.js + centrifuge.js ?

### ISSUE THREAD

**Issue by OverseeRr** [centrifugal/centrifuge-js#80]
In one of my projects I do not have the ability to include **<script src="centrifuge.js"></script>** into web page directly, the only available way to include script is like this:
```
require([
    'centrifuge.js'
], function(c) {
	var centrifuge = new Centrifuge('...', {"debug": true});
});
```
Ends up with error: **ReferenceError: Centrifuge is not defined**

Is there any solutions?

**Comment by FZambia** [comment]
Hi, as far as I remember how requirejs work you may need to write it like this:
```
require([
    'centrifuge.js'
], function(Centrifuge) {
	var centrifuge = new Centrifuge('...', {"debug": true});
});
```

Though I have not tested this. Have you tried this way?

**Comment by OverseeRr** [comment]
Yes. Same error(((

**Comment by FZambia** [comment]
Ah :)  Personally never used requireJS before, just googled around - looks like the reason is that `centrifuge-js` uses named UMD modules (`Centrifuge` in our case). I've created a pen to show working integration with requireJS:

https://codepen.io/FZambia/pen/GLoYpX

Could you test the same with your local setup? If it works - please post full solution so I could update docs (or just send pull request yourself if you want).

**Comment by OverseeRr** [comment]
Same here, using requireJS for the first time. Other modules in the project work without any problems by simple **require()** so didn't think about **require.config()**

```
require.config({
  paths: {
      'Centrifuge': 'libs/js/centrifuge.min'
  }
});

require([
    'Centrifuge'
], function(Centrifuge) {
	let centrifuge = new Centrifuge('wss://my-server/connection/websocket');
});
```
This solution helped. Thanx a lot :)
